spring.application.name=config-server
server.port=8888


spring.cloud.config.server.git.uri=https://github.com/wxbing000/springCloudConfig
spring.cloud.config.server.git.searchPaths=respo
spring.cloud.config.label=master
spring.cloud.config.server.git.username=wxbing000@163.com
spring.cloud.config.server.git.password=@1239fjk